---
- name: Download Sauce Connect
  get_url: url=https://saucelabs.com/downloads/sc-{{ sc_version }}-{{ sc_os }}.tar.gz
           dest=/usr/local/src/sc-{{ sc_version }}-{{ sc_os }}.tar.gz

- name: Extract and install Sauce Connect
  unarchive: src=/usr/local/src/sc-{{ sc_version }}-{{ sc_os }}.tar.gz
             dest=/opt
             copy=no
             creates=/usr/local/sc-{{ sc_version }}-{{ sc_os }}
